### ISSUE TITLE
[META] Add interim form state on form-based modals

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/dashboards-flow-framework#446]
Modals should persist their own form state, and only update when users explicitly want to. The following modals should follow this pattern:

- [x] source data / ingest docs editor modal #445 
- [x] input transform modal - #456 
- [x] output transform modal - #456 
- [x] query editor modal - #450 

Prompt and query override modals leaving for now; these will likely be refactored and/or removed in later changes.

**Comment by ohltyler** [comment]
All PRs merged.
