### ISSUE TITLE
[META Support confirmations when navigating away from unsaved changes

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/dashboards-flow-framework#469]
There are several scenarios where we should warn users when exiting the edit page if there are unsaved changes. This includes:

- [ ] refreshing browser
- [ ] navigating forward/back from browser. NOTE: testing with [react router v5 Prompt](https://v5.reactrouter.com/core/api/Prompt) in the `WorkflowDetailHeader` component seems to render multiple times. Seems like a known issue, and is historically buggy, and removed in v6. Further native js solutions may be the only path forward here.
- [ ] navigation within OSD (breadcrumbs, different applications, etc.). NOTE: have run into same issues described above ^
- [ ] navigation within plugin (clicking 'Close' button). NOTE: have run into same issues described above
