### ISSUE TITLE
[META] [FEATURE] Simplify model input configurations

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/dashboards-flow-framework#491]
To flexibly handle all input types for a model (static fields, transforms, document fields, templates, etc.), we can have a more structured UI for configuring. The current UI just allows freeform text or a dropdown of available fields, if found. In the end, it is all converted just to text anyways. Below are some of the target mockups highlighting the different input types we should explicitly show:

![Screenshot 2024-11-20 at 9 57 17 AM](https://github.com/user-attachments/assets/f5298007-688a-4067-8db4-b99078278f9f)
![Screenshot 2024-11-20 at 9 57 26 AM](https://github.com/user-attachments/assets/b1ac5175-6489-403c-a424-55c7ff5be9c7)

To accomplish this, we will need to do the following:
- [x] refactor the ML processor components to be more customized #492 
- [x] update the underlying UI config for input transforms - we need to persist some metadata determining the different "types" offered (template vs. document field etc.) #495 
- [x] add abstraction logic to convert constants/templates into the `model_config` field for the ML processor when converting to a final template containing the JSON config body, and leaving document field / transform definitions as values for the input maps #495 
- [x] add & update existing transform modals to support both template configuration, and transform configuration, similar to what exists already #495 / #502
- [x] finalize what will be done for the outputs - do we duplicate some of the logic? The key difference is static values will not be supported - only JSONPath / selecting fields from the model output will be supported. #502

**Comment by kamingleung** [comment]
A small adjustment to UI for Prompt and Expression:
- For initial state, we can remove the pencil icon in the "Configure" button. Click on the Configure button will open the prompt/expression modal.
- For the inputted state, we can use plain text and the pencil icon. Clicking on the pencil icon will open the prompt/expression modal. The read only text field may confuse users into thinking it can be editable inline.

![image](https://github.com/user-attachments/assets/b8d659b0-d3b9-424e-acea-8bc4b2028a01)
